### ISSUE TITLE
Reproduce results in the paper

### ISSUE THREAD

**Issue by kparichay** [nttcslab-nlp/doc_lm#1]
Hi
I am trying to reproduce the results in the paper.
Running the current version of the code for PTB dataset gives 55.75 and 53.43 PPW for validation and test dataset respectively (without fine-tune).

This is almost 0.5~1.0 PPW higher compared to the results in Table 7 in the paper.

I ran the command to train as provided in the README.md

Can you pleas provide the settings used so as to reproduce the results in the paper.

Thanks

**Comment by takase** [comment]
Table 7 indicates fine-tuned results.
So, if you try fine-tuning, you probably obtain similar scores in the paper (in PTB, valid: 54.62, test: 52.87).
Would you try to apply finetune.py to the trained model?

#At first training step, I think your result is similar to ours.
#In PTB, we achieved valid: 55.45, test: 53.44 with GTX1080Ti, and valid: 55.21, test: 53.44 with P100.

**Comment by kparichay** [comment]
I thought that the results mentioned in table 7 are with and without fine-tuning.
I will do fine-tuning to the model to match your results.

Thanks for the explanation.
